app/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import SubmitField, StringField, SelectField
from wtforms.validators import DataRequired

app/predict_association/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField,SelectField
from wtforms.validators import DataRequired


class AssociationForm(FlaskForm):
    product =SelectField('product', validators=[DataRequired()],choices=['Wines','Fruits','Sweets','Gold','Meat','Fish'])
    segment =SelectField('segment', validators=[DataRequired()],choices=['Frequent Buyer','Normal Buyer','Low Buyer'])
    submit = SubmitField('Submit')

app/predict_cluster/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import SubmitField, SelectField
from wtforms.validators import DataRequired

class PredictForm(FlaskForm):
    input_file = FileField('input_file',validators=[DataRequired(),FileAllowed(['csv'])])
    cluster_model = SelectField('cluster_model',validators=[DataRequired()],choices=['K-means','Gaussian Mixtures'])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
import pickle

app = Flask(__name__)
app.config['SECRET_KEY'] = '5073a7594ddec9d863ecc03aa8edc161'

with open(f'./app/cpr_gmm.pkl', 'rb') as f:
    model_gmm = pickle.load(f)


with open(f'./app/cpr_kmeans.pkl', 'rb') as f:
    model_kmeans = pickle.load(f)

with open(f'./app/association.pkl','rb') as f:
    model_association = pickle.load(f)

from app.main.routes import main
from app.predict_cluster.routes import clusters
from app.predict_association.routes import association
from app.utils.utils import utils

app.register_blueprint(main)
app.register_blueprint(clusters)
app.register_blueprint(association)
app.register_blueprint(utils)

app/main/__init__.py
# This file tells python that this directory is a package

app/main/routes.py
from flask import render_template, Blueprint

main = Blueprint('main', __name__)


import logging
logging.basicConfig(filename='./app/log_info.log',level=logging.DEBUG,filemode='w',
                    format='%(asctime)s:%(levelname)s:%(message)s')

@main.route('/')
@main.route('/landing')
def landing():
    logging.info('starting landing page')
    return render_template('landing.html',title='landing_page')

@main.route('/home')
def home():
    logging.info('starting home page')
    return render_template('home.html',title='home')

@main.route("/about")
def about():
    return render_template('about.html', title='about')

app/predict_association/__init__.py
# This file tells python that this directory is a package

app/predict_association/routes.py
from flask import Blueprint, render_template,request
from app.predict_association.forms import AssociationForm
from app import model_association

association = Blueprint('association', __name__)


import logging
logging.basicConfig(filename='./app/log_info.log',level=logging.DEBUG,filemode='w',
                    format='%(asctime)s:%(levelname)s:%(message)s')

@association.route("/predict_association",methods=['GET','POST'])
def predict_association():
    form = AssociationForm()
    if request.method == 'GET':
        return render_template('association.html',title='predict association',form=form,v = False)
    if form.validate_on_submit():
        product = form.product.data
        segment = form.segment.data
        logging.info('input successful')
        target = '{\'%s_seg_%s\'}' %(product,segment)
        output = model_association[model_association['consequents'].astype(str).str.contains(target, na=False)].sort_values(by='confidence', ascending=False)
        logging.info('creating output')
        first,second = segment.split(' ')
        filename = product +'_'+ first + '_' + second + '.xlsx'
        output.to_excel('./app/static/files/'+filename,index=False)
        logging.info('output file created successfully')
        return render_template('association.html',title='predict association',form=form,v=True,file=filename)

app/predict_cluster/routes.py
import pandas as pd
from flask import Blueprint, render_template,request
from app.predict_cluster.forms import PredictForm
from app.predict_cluster.utils import predict_clusters


clusters = Blueprint('clusters', __name__)


import logging
logging.basicConfig(filename='./app/log_info.log',level=logging.DEBUG,filemode='w',
                    format='%(asctime)s:%(levelname)s:%(message)s')

@clusters.route('/predict_cluster', methods=['GET', 'POST'])
def predict_cluster():
    form = PredictForm()
    if  request.method == 'GET':
        return render_template('predict_cluster.html',title='predict clusters',form=form,v=False)
    if form.validate_on_submit():
        file_input=request.files['input_file']
        ml_model = form.cluster_model.data
        logging.info('input successful')
        data= pd.read_csv(file_input)
        logging.info('converted to csv')
        output_data = predict_clusters(data,ml_model)
        output_data.to_csv('./app/static/files/predicted_clusters.csv')
        logging.info('output csv file successfully created')
        filename = 'predicted_clusters.csv'
        return render_template('predict_cluster.html',title='predict clusters',form=form,v=True,filename=filename)

app/templates/about.html
{% extends 'layout.html' %}

{% block content %}
    <div style="margin-bottom: 100px;">
        <h3 id="special">CUSTOMER PERSONALITY REVIEW</h3>
        <article class="content-section">
            <h4 class="article-title"> Objective: </h4>
            The project is about analyzing the behaviour of the customers related to the company 
            depending upon various factors provided in the dataset.
            The analysis will help the company to create groups of customers with same behaviour
            towards the company and also decide different marketing strategies for different 
            groups.
        </article>
        <article class="content-section">
            <h4 class="article-title"> Sections: </h4>
            The website contains two sections -  
            <ul type="none">
                <li>
                    <h5> Predict_cluster: </h5>
                    This sections takes dataset from the user and assigns the clusters based 
                    on the ML algorithm user selected. 
                    The choice between K-means clustering and Gaussian Mixtures.
                    The dataset with the clusters info. will be returned.
                    This section will help company to know about it's customers and plan strategies.
                </li>
                <li>
                    <h5> Predict_association: </h5>
                    This sections takes dataset from the user and provides data about the association
                    of the different products based on the customers purchasing habits.
                    The dataset with the association rule info. of the selected product will be returned.
                    This section will help company to know the potential targets for the marketing of
                    the product.
                </li>
            </ul>
        </article>
        <article class="content-section">
            <h4 class="article-title">Dataset Used: </h4>
            <a href="https://raw.githubusercontent.com/amankharwal/Website-data/master/marketing_campaign.csv"> Dataset</a>
        </article>
        <article class="content-section">
            <h4 class="article-title">Algorithms Used: </h4>
            <ul type="none">
                <li>
                    <h5> K-means clustering: </h5>
                    <a href="https://towardsdatascience.com/understanding-k-means-clustering-in-machine-learning-6a6e67336aa1">click for more</a>
                </li>
                <li>
                    <h5> Gaussian Mixtures: </h5>
                    <a href="https://www.analyticsvidhya.com/blog/2019/10/gaussian-mixture-models-clustering/">click for more</a>
                </li>
                <li>
                    <h5> Apriori:</h5>
                    <a href="https://www.javatpoint.com/apriori-algorithm-in-machine-learning">click for more</a>
                </li>
                <li>
                    <h5>Association rules: </h5>
                    <a href="https://www.javatpoint.com/apriori-algorithm-in-machine-learning">click for more</a>
                </li>
            </ul>
        </article>
        <article class="content-section">
            <h4 class="article-title">Technologies Used :</h4>
            <ul type="none">
                <li>
                    <h5> Python: main programming language </h5> 
                </li>
                <li>
                    <h5> Flask: as python framework </h5>
                </li>
                <li>
                    <h5> WTF forms: to create forms</h5>    
                </li>
                <li>
                    <h5> sklearn: to perform machine learning operations</h5>    
                </li>
                <li>
                    <h5> Numpy: to perform scientific computing in python</h5>    
                </li>
                <li>
                    <h5> Pandas: as data analysis and manipulation tool</h5>    
                </li>
            </ul>
        </article>
    </div>
    <footer>
        <p>Created By Harshavardhan Kamble <span>&copy</span> ,09/2021</p>
    </footer>
{% endblock content %}

app/templates/association.html
{% extends 'layout.html' %}


{% block content%}
  <div class="content-section">
    <form action="" method="POST">
      {{ form.hidden_tag() }}
      <fieldset>
        <legend class="border-bottom mb-4">Association</legend>
        <div class="form-group">
          {{ form.product.label(class='form-control-label') }}
          
          {% if form.product.errors %}
            {{ form.product(class="form-control form-control-lg is-invalid")}}
            <div class="invalid-feedback">
              {% for error in form.product.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.product(class='form-control form-control-lg') }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.segment.label(class='form-control-label') }}
          
          {% if form.segment.errors %}
            {{ form.segment(class="form-control form-control-lg is-invalid")}}
            <div class="invalid-feedback">
              {% for error in form.segment.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.segment(class='form-control form-control-lg') }}
          {% endif %}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class='btn btn-outline-info') }}
      </div>
    </form>
  </div>
  {% if v == True: %}
    <div class="content-section">
      <span>{{ file }}</span><button class="btn btn-outline"><a href="{{ url_for('utils.download_file', filename='static/files/'+file) }}">Download File</a></button>
    </div>
  {% endif %}
{% endblock content %}

app/templates/home.html
{% extends 'layout.html' %}
{% block content %}
    <div class="content-section">
        <h3 class="changing_h2"><a href="{{ url_for('clusters.predict_cluster') }}">1.Predict Cluster</a></h3>
        <div>
            <h4>Inputs:</h4>
            <ul type="none">
                <li>Dataset with colummns:
                    <ol type="1">
                        <li>Income :  income of the customer</li>
                        <li>TotalAmtSpent : Total amt. spent on different products</li>
                        <li>
                            Relation : how many years customer related to company i.e. current_year-joining year
                        </li>
                    </ol>
                </li>
                <li>Data Model: Kmeans, GaussianMixtures</li>
            </ul>
        </div>
        <div>
            <h4>Output:</h4>
            <ul type="none">
                <li>csv file with clusters column appended, the clusters being:
                    <ol type="numbers">
                        <li>Ace: High salary, High spending, Old relation</li>
                        <li>Diamond: High salary, High spending, New relation</li>
                        <li>Platinum: Low salary, Low spending, New relation</li>
                        <li>Gold: Low salary, Low spending, Old relation</li>
                    </ol>
                </li>
            </ul>
        </div>
    </div>
    <div class="content-section">
        <h3 class="changing_h2"><a href="{{ url_for('association.predict_association') }}">2.Predict Association</a></h3>
        <div>
            <h4>Inputs:</h4>
            <ul type="none">
                <li>Product Name</li>
                <li>Segment Name</li>
            </ul>
        </div>
        <div>
            <h4>Output:</h4>
            <ul type="none">
                <li>Excel file with association rule of the product</li>
            </ul>
        </div>
    </div>
{% endblock content %}

app/templates/landing.html
{% block content%}
    <style>
        body{
            background:aquamarine;
        }
        .container {
            width: 70%;
            height: 40%;
            margin: 200px 250px 20px 250px;
            border: 1px solid #1b7777;
            padding: 0px;
            background: #228b8b;
        }
        
        #title {
            color: white;
            font-size: 50;
            margin: 50px 150px;
        }
        button {
            padding: 10px 20px;
            margin:0px 700px;
            background-color:aquamarine;
            border: 2px solid blue;
        }
        @media screen and (max-width:850px){
            .container{
                width: 60%;
                height: 30%;
                margin: 200px 150px 20px 200px;
                border: 1px solid #1b7777;
                padding: 0px;
                background: #228b8b;
            }
            #title {
                color: white;
                font-size: 40;
                margin: 30px 150px;
                margin-left:100px;
            }
            button{
                padding: 10px 20px;
                background-color:aquamarine;
                border: 2px solid blue;
                margin: 0px 400px;
            }
        }
        @media screen and (max-width:670px){
            .container{
                width: 60%;
                height: 30%;
                margin: 200px 100px 20px 150px;
                border: 1px solid #1b7777;
                padding: 0px;
                background: #228b8b;
            }
            #title {
                color: white;
                font-size: 30;
                margin: 15px 150px;
                margin-left:50px;
            }
            button{
                padding: 10px 20px;
                background-color:aquamarine;
                border: 2px solid blue;
                margin: 0px 250px;
            }
        }
    </style>
    <div class="container">
        <h1 id="title">CUSTOMER PERSONALITY ANALYSIS</h1>
    </div>
    <button><a href="{{ url_for('main.home') }}" style="text-decoration: none; color:black"><strong>Enter</strong></a></button>
{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='main.css') }}">
  {% if title %}
    <title>Customer_Personality_Review - {{title}}</title>
  {% else %}
    <title>Customer_personality_Review</title>
  {% endif %}
</head>
<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="/">CPR</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
            <a class="nav-item nav-link" href="{{ url_for('clusters.predict_cluster') }}">Predict_cluster</a>
            <a class="nav-item nav-link" href="{{ url_for('association.predict_association') }}">Predict_association</a>
            <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% with messages = get_flashed_messages(with_categories = true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}">
                {{message}}
              </div>
            {% endfor %} 
          {% endif %}       
        {% endwith %}
        {% block content %}{% endblock %}
      </div>
    </div>
  </main>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script></body>
</html>

app/templates/predict_cluster.html
{% extends 'layout.html' %}


{% block content%}
  <div class="content-section">
    <form action="" method="POST" enctype="multipart/form-data">
      {{ form.hidden_tag() }}
      <fieldset>
        <legend class="border-bottom mb-4">{{ title }}</legend>
        <div class="form-group">
          {{ form.input_file.label(class='form-control-label') }}
          
          {% if form.input_file.errors %}
            {{ form.input_file(class="form-control form-control-lg is-invalid")}}
            <div class="invalid-feedback">
              {% for error in form.input_file.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.input_file(class='form-control form-control-lg') }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.cluster_model.label(class='form-control-label') }}
          
          {% if form.cluster_model.errors %}
            {{ form.cluster_model(class="form-control form-control-lg is-invalid")}}
            <div class="invalid-feedback">
              {% for error in form.cluster_model.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.cluster_model(class='form-control form-control-lg') }}
          {% endif %}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class='btn btn-outline-info') }}
      </div>
    </form>
  </div>
  {% if v == True: %}
    <div class="content-section">
      <span>{{ filename }}</span><button class="btn btn-outline"><a href="{{ url_for('utils.download_file', filename='static/files/predicted_clusters.csv') }}">Download File</a></button>
    </div>
  {% endif %}
{% endblock content %}